### ISSUE TITLE
function "detailed_entries"

### ISSUE THREAD

**Issue by shawngraham** [ropenscilabs/vitae#14]
Hi,

Saw a mention of this package on twitter, thought I'd try it out. Have installed it with devtools, and dependencies. I've authenticated orcid, and am trying to pass my orcid to it. Getting this error, which seems odd. I think I must be missing something in my setup? Using the code snippet for '#education' from your slides. Thanks.

```
Error in detailed_entries(., what = `role-title`, when = glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"),  : 
  could not find function "detailed_entries"
Calls: <Anonymous> ... eval -> _fseq -> freduce -> withVisible -> <Anonymous>
Execution halted
```

**Comment by mitchelloharawild** [comment]
You'll need to load in the vitae package in your setup code chunk.
You can check the njtierney folder or [my CV](https://github.com/mitchelloharawild/CV) for an example of how the package can be used.

**Comment by mitchelloharawild** [comment]
f843b39 updates the skeleton template to include loading the vitae package. Hopefully this makes things easier.

**Comment by shawngraham** [comment]
Cool, thank you! Looking at the njtierney folder was very helpful, as I was able to replicate that successfully. But when I put my own orcid into the rmd, it fails again with the error message - so the error is on my end, with incomplete fields in my orcid profile.
