### ISSUE TITLE
Possible to control templates within .Rmd?

### ISSUE THREAD

**Issue by Aariq** [ropenscilabs/vitae#19]
I'm not sure if this is possible, because I don't know much about pandoc or latex.  Would it be possible to control some basic options like margins and font sizes through the .Rmd document rather than having to edit the template?  I love this package so far for its simplicity, but I wonder if there is a middle ground that allows some flexibility without having to all-out edit the latex templates.

**Comment by mitchelloharawild** [comment]
A variety of options can be controlled within the .Rmd document.
A list of options (including font size) that can be controlled in the YAML header can be found in this vignette: https://ropenscilabs.github.io/vitae/articles/extending.html

If there is a common element that you'd like to control, but cannot using those options, we can see if it can be added.

**Comment by MokeEire** [comment]
For posterity's sake, the link above is broken and I can't quickly find a working link (although it works within RStudio: `vignette("extending", package = "vitae")`

**Comment by mitchelloharawild** [comment]
Thanks, the updated URL is https://pkg.mitchelloharawild.com/vitae/articles/extending.html
@stefaniebutland would it be possible to redirect `ropenscilabs.github.io/vitae/*` to `pkg.mitchelloharawild.com/vitae`?

**Comment by jeroen** [comment]
Oki, done :) https://github.com/ropenscilabs/ropenscilabs.github.io/commit/262ae07db4bdcad03930c7eae2eadd714896e31d
