### ISSUE TITLE
I Just try to knit the awesome template on Windows 10 and got errror

### ISSUE THREAD

**Issue by xiaodaigh** [ropenscilabs/vitae#20]
the top part is like this

```r
---
name: Marie Curie
position: "Professor"
address: "School of Physics & Chemistry, Ãcole Normale SupÃ©rieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---
```

so it complained but if I remove the weird characters **Ã** and **Ã©** then it compiles (knits)

**Comment by robjhyndman** [comment]
Presumably your text editor is not set up for UTF8 encoding. If you are using Rstudio, see https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding
