### ISSUE TITLE
Reclassify repo language as R

### ISSUE THREAD

**Issue by jsta** [ropenscilabs/vitae#21]
Github is calling `vitae` a `tex` repo. What do you think about adding a `.gitattributes` file to force an `R` classification? Happy to submit a PR following https://github.com/github/linguist#vendored-code

Something like: 

```
*.sty linguist-vendored
*.cls linguist-vendored
*.tex linguist-vendored
*.R linguist-vendored=false
```

**Comment by mitchelloharawild** [comment]
Sounds good, feel free to submit a PR :+1:
