### ISSUE TITLE
Support for hyperlinks in `detailed_entries`

### ISSUE THREAD

**Issue by Runze** [ropenscilabs/vitae#23]
Hi! I really like this package and find it very helpful :)

I have one question: it seems to me that the current `detailed_entries` doesn't display hyperlinks the way normal markdown does. For example, in the following simplified example, I was hoping to display `[url_name](www.google.com)` as a hyperlink but the result is the raw string as is.

```r
tibble::tribble(
  ~what,
  "[url_name](www.google.com)"
) %>%
  detailed_entries(
    what = what
  )
```
Is it possible to add a support for that or is there a workaround for it?

Thank you!

**Comment by mitchelloharawild** [comment]
I've added support for providing LaTeX code in the entries now, which is enabled by setting `.protect=FALSE`.
```r
tibble::tribble(
  ~what,
  "\\href{www.google.com}{www.google.com}"
) %>%
  detailed_entries(
    what = what,
    .protect = FALSE
  )
```

**Comment by Runze** [comment]
Thank you! Can confirm it works now :) 👍
