### ISSUE TITLE
cvskills

### ISSUE THREAD

**Issue by mohdasti** [ropenscilabs/vitae#25]
Very good job and beautiful format indeed!
I had two issues so far:
1. R was unable to run 'cvskill' function. 
2. it is not urgent, but in Teaching Associate part, it'd be nice to mention the University name and location once, and then add each class and dates accordingly. The repetition of those information is not appealing.

---

Brief description of the problem

```r
 cvskill("Data Analysis", c("Visualisation", "Data Cleaning", "Forecasting", "Modelling", "Communication", "Inference", "Machine Learning", "Web Scraping"))
 cvskill("Programming", c("R", "Python", "SQL", "Java", "C", "C++", "HTML/CSS", "TeX", "MATLAB")) 
 
```

**Comment by mitchelloharawild** [comment]
The `vitae` package does not provide a cvskill function.
Do you have an example of the document with the teaching associate example?

**Comment by mohdasti** [comment]
In your sample [CV](https://github.com/mitchelloharawild/CV/blob/master/CV.Rmd), teaching associate segment are all in one piece. Presumably, because of the fact that university and the date are _identical_ (this is my understanding). However, by changing the date from "Jan. 2016 - Present" to something else, say for another semester, it will generate whole new section with your university and its location, which seems redundant. We are still talking about our experiences within the same institution. 
With regards to cvskill function, since it was part of your CV sample, deactivated though, I thought this is part of your package.
