### ISSUE TITLE
Error compiling/previewing templates

### ISSUE THREAD

**Issue by daranzolin** [ropenscilabs/vitae#29]
Excited to try this package, but I've tried previewing each template (without modification) in both the CRAN and development versions and encounter a persistent error:

```
Error: Failed to compile <file name>.tex
In addition: Warning message:
In system2(..., stdout = FALSE, stderr = FALSE) : error in running command
Execution halted
```
I also tried pasting the contents of one of the featured examples.

**Comment by mitchelloharawild** [comment]
Do you have LaTeX installed? If not, you can easily install it with [tinytex](https://yihui.name/tinytex/).
```r
install.packages('tinytex')
tinytex::install_tinytex()
```

**Comment by daranzolin** [comment]
🙈 🙈Can we pretend this conversation never happened! I didn't know.
