### ISSUE TITLE
Template directives in YAML?

### ISSUE THREAD

**Issue by basille** [ropenscilabs/vitae#36]
Hi,

I'm trying to switch my old CV, manually curated, to a semi-automated version using `vitae`. My CV is based on `moderncv`, which is already a good start. However, I don't use the default theme (`casual`), but another one called `classic`. In LaTeX, the theme is set with this directive in the preamble of the file:

```latex
\moderncvtheme{classic}
```

Is there a way to set this option through the YAML header of the RMarkdown file?

Other options include the color, for instance:

```latex
\moderncvcolor{blue}
```

There might be others too…

Thanks to the developers of this great package, very useful!

**Comment by YoJimboDurant** [comment]
The classic cv looks nice - I was able to change the tex output and change the tex file and then compile the document, although I needed to make some adjustments to the font size in my name, and it also looks like some adjustments need to be made to the email. It would be nice to have the ability to adjust the output options in the yaml.

**Comment by mitchelloharawild** [comment]
Adding support for other moderncv themes is definitely planned. It would
probably be best suited to different output formats for each theme.

Customisation of elements specified in the yaml header would also be nice.
I'll have a think about how this can be done most appropriately.

**Comment by mitchelloharawild** [comment]
On further thought, I think this is better suited as an argument to the `moderncv` template.
I'll try to find time to implement it this week.

**Comment by basille** [comment]
Thanks for looking into it!

**Comment by mitchelloharawild** [comment]
This should now be possible! :tada: 

```r
output: 
  vitae::moderncv:
    theme: classic
```

**Comment by gfleetwood** [comment]
> This should now be possible! 
> 
> ```r
> output: 
>   vitae::moderncv:
>     theme: classic
> ```

@mitchelloharawild Customizing the theme produces an error for me.

```
Error in base_format(toc = toc, number_sections = number_sections, fig_caption = fig_caption,  : 
  unused argument (theme = "classic")
Calls: <Anonymous> ... <Anonymous> -> cv_document -> <Anonymous> -> pdf_book
Execution halted
```

**Comment by mitchelloharawild** [comment]
Do you have the development version of the package installed?
The CRAN version hasn't been updated for this change yet.

**Comment by gfleetwood** [comment]
That was the problem. Thanks. On a slightly related note, how would I change the color of headings in awesomecv by adding `\colorlet{awesome}{black}` (as suggested [here](https://github.com/posquit0/Awesome-CV/issues/75))?

**Comment by mitchelloharawild** [comment]
I've done something similar for my CV:
https://github.com/mitchelloharawild/CV/blob/edf7283ee691052a26d7a60ce4a846e2945b9ab0/CV.Rmd#L13

Change the numbers to whichever hexadecimal colour you want.

**Comment by gfleetwood** [comment]
Great. Thanks again.
