### ISSUE TITLE
Homepage link not working

### ISSUE THREAD

**Issue by KateJohnson** [ropenscilabs/vitae#38]
The `www:` link is not working in the moderncv template. When I render to pdf it shows up as 'http//[address]' rather than 'http://[address]'

The same issue is in the [sample CV](https://github.com/Aariq/curriculum-vitae/blob/master/Committee%20Update%20Fall%202018/Committee_Update_Fall_2018.pdf) shown in the Readme.

**Comment by mitchelloharawild** [comment]
I can't reproduce this with the latest version of vitae. I completely re-implemented the moderncv template <10 hours ago to support themes, which appears to have fixed this issue.

Please update the package, delete the .cls files in your working folder and try again.

**Comment by KateJohnson** [comment]
Thanks for your quick response! 

I updated the package, but am now having problems with tinytex not being able to find l3regex.sty in this new version.
I'll submit a new issue if I can't get it sorted.
