### ISSUE TITLE
! Package biblatex Error: Category 'bibRefereed journal papers' already declared.

### ISSUE THREAD

**Issue by michielvandijk** [ropenscilabs/vitae#39]
Similar to the RobHyndmanCV.rmd, I tried to create more than two bib lists (see below). However, when I do this, I get the following error: ! Package biblatex Error: Category 'bibRefereed journal papers' already declared. When I run only one of the scripts (thesis or research-papers) it works fine. First I thought it could be related to my Miktex installation. I deleted it and replaced with tinytex but the error remains, hence, I assume it must be something in the package.

## PhD thesis
```{r thesis}
bibliography_entries("bib/VanDijk.bib", startlabel = "papersstart") %>%
  filter(bibtype == "PhdThesis")
```

## Refereed research papers
```{r research-papers}
# Normal articles excluding editorials
bibliography_entries("bib/VanDijk.bib") %>%
 filter(bibtype == "Article") %>%
  arrange(year, author)
```

**Comment by robjhyndman** [comment]
Can you set output to
```
output:
  vitae::hyndman:
    keep_tex: true
```
and then post the resulting tex and bib file.

**Comment by michielvandijk** [comment]
Here they are, uploaded as zip

[CV.zip](https://github.com/ropenscilabs/vitae/files/2857627/CV.zip)

**Comment by michielvandijk** [comment]
[Michiel_van_dijk_cv_test.log](https://github.com/ropenscilabs/vitae/files/2857629/Michiel_van_dijk_cv_test.log)

Perhaps useful as well, the log file.

**Comment by robjhyndman** [comment]
Can you also provide the Rmd?

**Comment by michielvandijk** [comment]
[Michiel_van_dijk_cv_test.zip](https://github.com/ropenscilabs/vitae/files/2858029/Michiel_van_dijk_cv_test.zip)

**Comment by robjhyndman** [comment]
That compiles for me without errors. Are you using the latest github version of vitae?

**Comment by michielvandijk** [comment]
I am not. I installed from CRAN. I will update now and retry.

**Comment by michielvandijk** [comment]
Works! So I guess this bug was fixed in the Github version. Thanks for the support! Great package.

**Comment by robjhyndman** [comment]
Actually, not so much a bug as a change in how the function is used. Previously, the title was an argument in bibliography_entries() and it had to be unique for each entry. If you didn't use it, the default was "Refereed journal papers". So if you used two or more bibliography_entries() calls leaving title as default, it created this error. We now don't use a title argument and generate a unique identifying string on the fly.
