### ISSUE TITLE
Fix indentation of awesomecv

### ISSUE THREAD

**Issue by mitchelloharawild** [ropenscilabs/vitae#44]
If this is inconsistent with the awesomecv template, this should be fixed.
As mentioned in #43 and on Twitter.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/ropenscilabs/vitae/commit/d52f356f6ae54a84fd178359432b7e5cba30e8ab

**Comment by januz** [comment]
That's great. Thank you so much! One more issue I see is that the spacing between different items within one group seems to be too narrow. See this screenshot (still with the wrong indentation, but the spacing remains the same after the fix):

![image](https://user-images.githubusercontent.com/1440498/52836987-c5eca900-30a1-11e9-9d5e-921a5ee768f6.png)

**Comment by robjhyndman** [comment]
OK. I've tweaked it. Delete your .cls file and try to recompile using the updated version.

**Comment by januz** [comment]
Looks great now. Thank you!!
