### ISSUE TITLE
Vignette for interfacing with other packages (rorcid, scholar, etc.)

### ISSUE THREAD

**Issue by jgeller112** [ropenscilabs/vitae#50]
I am unable to knit the document when I try to pull data from my ORCID account. I have tried everything suggested by ?orid_auth.  I get the following error: 

Error: In non-interactive environments, please set ORCID_TOKEN env to a ORCID access token, see ?orcid_auth for details
Execution halted

Any solutions to this?

**Comment by mitchelloharawild** [comment]
As the error suggests, knitting a document is a non-interactive environment. You will need to set the ORCID_TOKEN to your R environment. The help file for `orcid_auth` should go into a bit more detail than I will here, but essentially:

Open your .Renviron file with `usethis::edit_r_environ()`, and add a new line containing `ORCID_TOKEN = dc0a6b6b-b4d4-4276-bc89-78c1e9ede56e`. This is an example token - you will need to obtain your own token using `rorcid::orcid_auth()`.

**Comment by jgeller112** [comment]
That worked! Thanks! Do you think it would benefit others by including that extra bit of detail in your vignettes? It could be that I am just clueless about changing things like that in my R environment.

**Comment by mitchelloharawild** [comment]
Sure thing. Updated the issue title for this.
