### ISSUE TITLE
Centering 'name' and justifying 'about me'

### ISSUE THREAD

**Issue by jantleon** [ropenscilabs/vitae#55]
Hello.

First of all, I'd like to thank Mitchell and Rob for their contribution to R community with this useful package. I'm using it in order to make a better CV and I'm very satisfied with it.

However, I'm having two issues that I need to solve. In Spain we use two surnames, so name's section has two lines. A good solution might be centering the text. I've been trying to modify the template but I don't have enough Latex knowledge to do that. Also I tried to include a \center in that part (but it doesn't work either):

---
name: \center JOSÉ ANTONIO \newline XXX YYY

In the same way, I want to justify the text that appears in About me's section. \justify is not working for me as \newline does.

Thank you for your help :D

**Comment by mitchelloharawild** [comment]
Which template are you using? Could you provide a sample of the YAML header which reproduces this?

**Comment by jantleon** [comment]
Yes, I'm using twentysecond template. The used code in vitae is:
---
name: NAME \newline SURNAME SURNAME
position: "xxx \\newline yyy"
phone: 111111111
profilepic: foto.png
email: "xxx@gmail.com"
github: xxx
linkedin: xxx
aboutme: " XX \\newline \\newline XX\\newline \\newline XXX \\newline \\newline XXX"
output: vitae::twentyseconds
---

I'd like to justify this part:
aboutme: " XX \\newline \\newline XX\\newline \\newline XXX \\newline \\newline XXX"

And center that one:
name: NAME \newline SURNAME SURNAME

But \justify and \center or \\justify and \\centering aren't working for me.

**Comment by robjhyndman** [comment]
These are not issues with the vitae package, but style choices in the twentysecond CV latex package. You can modify them by editing the twentysecondcv.cls class. The aboutme section can be made fully justified by removing \begin{flushleft} and \end{flushleft} on lines 171 and 173. You can center the name by modifying line 146 -- remove \raggedright and wrap the line inside \begin{center} and \end{center}.

**Comment by jantleon** [comment]
Problem solved. Thank you for your useful help @robjhyndman !
