### ISSUE TITLE
name input in R to firstname and surname in LaTeX

### ISSUE THREAD

**Issue by MoAnd** [ropenscilabs/vitae#56]
Is there a way to make the name input such that it splits up into the firstname and surname input in the LaTeX code when using the awesome-cv?

```r
name: Morten Andersen
output: vitae::awesomecv
```

In the original Awesome-CV the name input is done as `\name{Morten}{Andersen}` and the output is something similar to "Morten **Andersen**". However, the workaround of simply typing : 

```r
name: Morten **Andersen**
output: vitae::awesomecv
```

looks farily ugly in the footer.

Thank you :)

**Comment by mitchelloharawild** [comment]
Sounds good :+1: 
Added.

**Comment by MoAnd** [comment]
Thank you :)
However, I get an error now:
```
"template" (line 142, column 25):
unexpected " "
expecting "$endif$"
Error: pandoc document conversion failed with error 5
```

It won't even compile with only the name input.

**Comment by mitchelloharawild** [comment]
Oops, just put through a fix. Could you try again?

**Comment by MoAnd** [comment]
Working! :D Thanks! Keep up the good work!
