### ISSUE TITLE
(hidden) links in *_entries

### ISSUE THREAD

**Issue by MoAnd** [ropenscilabs/vitae#57]
Is there a way to include links and hidden links in the `*_entries` functions, such as in the `why` field or in the `where` field. 

I'm thinking something like the Markdown [link](www.google.com) or the LaTeX \href{}{} function, or at the very least a clickable url. 

```r
data <- tibble::tibble("what" = "Machine Learning", "when" = "April 2018", "with" = "Stanford University on Coursera", "where" = NA, "why" = *HIDDEN LINK HERE*)

data %>% detailed_entries(
    what = what, 
    when = when, 
    with = with,
    where = where,
    why = why
  )
```

Thank you :)

**Comment by Aariq** [comment]
Seems like the href{}{} trick works.  You just need to use two backslashes.
```
data <- tibble::tibble("what" = "Machine Learning", "when" = "April 2018", "with" = "Stanford University on Coursera", "where" = NA, "why" = "\\href{http://www.ericrscott.com/}{my website}")

data %>% detailed_entries(
    what = what, 
    when = when, 
    with = with,
    where = where,
    why = why
  )

**Comment by mitchelloharawild** [comment]
You may also need to set the argument `.protect=FALSE`, but the above should work.

**Comment by MoAnd** [comment]
Thank you, it works :)
