### ISSUE TITLE
New page/page break not being introduced properly

### ISSUE THREAD

**Issue by wyattmcdonnell** [ropenscilabs/vitae#58]
Hi there! I love the idea of using the R-Markdown-CSV trio to make a reproducible and easy-to-maintain CV. I ran into some `tlmgr` installation issues that were pretty easily resolved, but it might be worth documenting some of the LaTeX dependencies that are necessary for Mac OS X users (I'm happy to help with this if this is of interest to others). 

My main issue is that `vitae` and the `vitae::hyndman` template seem to be struggling to introduce a page break/push a section across multiple pages. In my CV, for instance, the publication section doesn't split properly across multiple pages (you can see this issue on **page 2**). 

I'm maintaining my information in a `.csv` file which I import as a tibble using `readr::read_csv()` and filter into section specific information using `dplyr::filter()`. For reference, below is a complete copy of the code in my `CV.Rmd` file (and a [Dropbox link to the knitted PDF, the original CV.Rmd file, and the .csv file I'm using](https://www.dropbox.com/sh/t2443f1runpgfs6/AADIG1RgsjskzWIpfgH6jjQsa?dl=0)):

```
---
name: Wyatt J. McDonnell, PhD
position: "Research Instructor"
address: "Dept. of Medicine, Vanderbilt University Medical Center, Nashville, TN, USA"
phone: +1 231 360 7775
www: bit.ly/WJM_Vanderbilt
email: "wyatt.j.mcdonnell@vanderbilt.edu"
twitter: wyattmcdonnell
github: wyattmcdonnell
linkedin: wyattmcdonnell
date: "`r format(Sys.time(), '%d %B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readr)
library(dplyr)
```
```
# At a glance
Wyatt is an American **systems immunologist** who uses **HIV and chronic viral infection** as models to understand **immune-mediated dysfunction and co-morbidities**. He is an avid reader, pianist, and data visualization enthusiast.  

 * 30 citations (Google Scholar)
 * **Google Scholar:** DclwmYAAAAAJ (https://bit.ly/WyattMcDonnellGoogleScholar)
 * **ORCID:** 0000-0003-3859-2067
 * **PubMed bibliography:** https://bit.ly/WyattMcDonnellPubMed
```

```
# Education
```
```{r education}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'education') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```

```
# Academic appointments
```
```{r appointments}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'appointment') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```

```
# Peer-reviewed publications
```
```{r publications}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'paper') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```

```
# Invited review articles
```
```{r reviews}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'review') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```

```
# Research program
```
```{r research}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'research') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```

```
# Awards and honors
```
```{r awards}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'award') %>%
  detailed_entries(what = what, when = when, with = with, where = where, why = list(item1, item2, item3, item4))
```
```
# Skills and expertise
```
```{r skills}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'skill') %>%
  brief_entries(what = what, when = when, with = with)
```
```
# Professional organizations
```
```{r professional organizations}
read_csv('WJM_CV_RMD.csv') %>%
  filter(type == 'organization') %>%
  brief_entries(what = what, when = when, with = with)
```

Is this happening because I'm using `detailed_entries()` instead of `bibliography_entries()`?

Thank you again for making and maintaining the `vitae` package!

Best wishes,
Wyatt

**Comment by mitchelloharawild** [comment]
> I ran into some tlmgr installation issues that were pretty easily resolved, but it might be worth documenting some of the LaTeX dependencies that are necessary for Mac OS X users (I'm happy to help with this if this is of interest to others).

I'm happy to accept a PR if you'd like to create a list of dependencies. Generally tlmgr dependency installation would happen automatically for most users, so hopefully it isn't too difficult to use vitae for most users.

> My main issue is that vitae and the vitae::hyndman template seem to be struggling to introduce a page break/push a section across multiple pages.

Looks like this is only happening with the `vitae::hyndman` output format. You should be able to use `detailed_entries()`, however this specific template is commonly used with primarily `bibliography_entries()`.

@robjhyndman Any suggestions on how this can be fixed for your template?

**Comment by robjhyndman** [comment]
`detailed_entries()` maps to a tabular environment which can't be split. We could map it to something page-breakable such as a longtable instead.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/ropenscilabs/vitae/commit/9911c81e0c658e9fde4f2c0c6739fe67d4e562c8
