### ISSUE TITLE
Fix awesome-cv issues

### ISSUE THREAD

**Issue by mitchelloharawild** [ropenscilabs/vitae#6]
@robjhyndman 

I've done as much LaTeX as I'm familiar with for the awesome-cv template, there's a few things left that I'm unsure about.

1. The font for the template requires (xe/lua)latex, can this be changed to work with the default R Markdown engines?
1. ~~The email yaml field is causing issues with href being defined twice (once from pandoc/R Markdown, and once in the cls for \email)~~

**Comment by robjhyndman** [comment]
1 is easy -- just add `latex_engine="xelatex"` in call to `pdf_document2()`
Fixed now

**Comment by mitchelloharawild** [comment]
Great, thanks!
