### ISSUE TITLE
change URL to docs.ropensci.org/vitae?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/vitae#60]
* as repo website

* in DESCRIPTION. you can run

```r
remotes::install_github("ropensci/rodev")
rodev::use_docs_link()
```

**Comment by maelle** [comment]
and in the Travis config you could get rid of the lines deploying the website.

For more info see https://ropensci.org/technotes/2019/06/07/ropensci-docs/

**Comment by mitchelloharawild** [comment]
Updated, thanks!
I'll keep the travis config for now, so that both copies of the pkgdown site are running. Later I should set up a redirect to the docs.ropensci.org/vitae
