### ISSUE TITLE
bibliography_entries() - tilde ('~') in file path leads to "! Missing \endcsname inserted"

### ISSUE THREAD

**Issue by RLumSK** [ropenscilabs/vitae#65]
## Description 
If the file path to the `.bib` file contains a `~` (tilde) building the CV stops with an odd LaTeX error `! Missing \endcsname inserted.`

In the function `knit_print.vitae_bibliography()` the call `paste("bib", x %@% "file")`
rewrites the input string without considering this particular case. 

### (1) 
The following call would lead to `! Missing \endcsname inserted.`
```r
bibliography_entries("~/Desktop/test.bib")
```

### (2) 

While this call (providing the full path) would work just fine
```r
bibliography_entries("/Users/pcuser/Desktop/test.bib")
```

## Proposed solution

Replacing line 50 in `bibliography.R` 

`paste("bib", x %@% "file", format((as.numeric(Sys.time())%%60)*1e5, nsmall = 0), sep = "-")`

by 

`paste("bib", dirname(x %@% "file"), format((as.numeric(Sys.time())%%60)*1e5, nsmall = 0), sep = "-")`

should fix the problem.

**Comment by mitchelloharawild** [comment]
Thanks!
