### ISSUE TITLE
Issues compiling awesome-cv on macOS

### ISSUE THREAD

**Issue by adamhsparks** [ropenscilabs/vitae#7]
Using `TinyTex` I cannot compile (knit) the awesome-cv template (as it's provided) even when I have the FontAwesome font installed.

I've had to add:
`
\defaultfontfeatures{Extension = .otf}
`

To line 77 of `awesome-cv.cls` , once I've done this it compiled (well, after I had to install some other fonts using `tlmgr` externally but that's not a `vitae` issue). Not sure if other systems are affected by this?

**Comment by adamhsparks** [comment]
On the plus side, this also fixed issues I was having compiling my on LaTex CV with FontAwesome.

**Comment by mitchelloharawild** [comment]
Resolved in b240961.

Thanks for the fix :+1:
