### ISSUE TITLE
The publication code provided in the vitae example produces a LaTex error

### ISSUE THREAD

**Issue by Dr-Joe-Roberts** [ropenscilabs/vitae#70]
Running the example code provided when creating a new `vitae` document produces the following error that I cannot find the answer to:

```
Warning messages:
1: In RefManageR::as.BibEntry(.) :
  rownames of data.frame not meaningful for creating keys
2: Package biblatex Warning: '\DeclareSortingScheme' is deprecated.
(biblatex)                Please use '\DeclareSortingTemplate'.
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please rerun LaTeX.
(biblatex)                Page breaks have changed. 
```

**Comment by mitchelloharawild** [comment]
These look like warnings, all of which are not too concerning and shouldn't impact the creation of a CV. Was the example able to produce a PDF?

**Comment by Dr-Joe-Roberts** [comment]
Yes, a PDF is still produced although the publications list isn't always rendered.

**Comment by RLumSK** [comment]
@Dr-Joe-Roberts: Accidentally I used TexLive-2018 after I switched to TexLive-2019 most of my problems disappeared. Maybe it helps, I can also confirm the warnings above.

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK I am not entirely certain about this as I am not overly familiar with LaTex. I am using TinyTex if that helps

**Comment by RLumSK** [comment]
@Dr-Joe-Roberts 'TinyTex' did not work for me for other reasons, so I had to switch to the full LaTeX release. So I guess I cannot help here, sorry.

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK Thanks for the update, my output displays correctly for the rest of CV just without displaying the publications! I have noticed that this seems to be an intermitent issue that arises only when using a .bib file for the publications.

**Comment by mitchelloharawild** [comment]
So I take it that updating from `\DeclareSortingScheme` to `\DeclareSortingTemplate` made no difference (other than removing the warning)? If you wanted to open another PR for this it can be done via a new branch.

As for publications not showing up, the warning from biblatex states 'Please rerun LaTeX.'. As far as I'm aware, this re-running should happen automatically, but if it doesn't the publications won't show up.

**Comment by RLumSK** [comment]
@mitchelloharawild sure, it just removes the warning, sorry, for not making this clear. I will make a new PR.

**Comment by mitchelloharawild** [comment]
Sounds great :smile:

**Comment by RLumSK** [comment]
@Dr-Joe-Roberts @mitchelloharawild is right, the LaTeX warning says 

> `LaTeX Warning: There were undefined references.` 

I am wondering whether it might be a problem with your cite keys in your BibTeX file? 
(If you are uncertain, just provide, e.g., two entries from you *.bib file)

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK The following are two example publications from my *.bib file:
```
@Article{1,
  title = {Terpene based biopesticides as potential alternatives to synthetic insecticides for control of aphid pests on protected ornamentals},
  author = {GH Smith and JM Roberts and TW Pope},
  journal = {Crop Protection},
  year = {2018},
  volume = {110},
  pages = {125-130},
  key = {1},
}

@Article{2,
  title = {Catch me if you can: the influence of refuge/trap design, previous feeding experience, and semiochemical lures on vine weevil (Coleoptera: Curculionidae) monitoring success},
  author = {JM Roberts and A Jahir and J Graham and TW Pope},
  journal = {Pest Management Science},
  year = {2019},
  volume = {In Press},
  key = {2},
}
```

This is the code I used to generate them in case it helps:
```
get_pubs <- get_publications("ZvELXScAAAAJ") %>%
  distinct(title, .keep_all = TRUE) %>%
  transmute(key = dplyr::row_number(),
                  title = as.character(title),
                  author = as.character(author),
                  journal = as.character(journal),
                  number,
                  year)
  
pub_details <- reshape2::colsplit(get_pubs$number, ", ", names = c("volume", "pages")) %>%
  transmute(volume = as.character(volume),
            pages = as.character(pages)) %>%
  mutate_if(is.character, tidyr::replace_na, "In Press")

pubs <- bind_cols(get_pubs, pub_details) %>%
  select(c(key, title, author, journal, year, volume, pages)) %>%
  transmute(bibtype = "Article",
                       key,
                       title = as.character(title),
                       author = as.character(author),
                       journal = as.character(journal),
                       year,
                       volume,
                       pages) %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib("roberts.bib")
```

**Comment by RLumSK** [comment]
@Dr-Joe-Roberts I tested various options. Unfortunately, I could not reproduce the behaviour. The publications were shown all the time after. My minimalistic example: 

```Rmd
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---
```

```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(scholar)

bibliography_entries("roberts.bib")
```

To produce 'roberts.bib' I used your code and I tried what you posted above. Both worked. 
I also saw the warnings you posted again but it still worked (I used the most recent vitae package from the master branch).

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK Thanks for testing and confirming, I will update `vitae` and see whether that resolves the issue...

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK Okay, so I have updated and rerun the code and realised that is produces this warning message when the publications aren't rendered: 
```
Warning messages:
1: In RefManageR::as.BibEntry(.) :
  rownames of data.frame not meaningful for creating keys
2: Package biblatex Warning: '\DeclareSortingScheme' is deprecated.
(biblatex)                Please use '\DeclareSortingTemplate'.
Package biblatex Warning: citation '1' was not found at all in the .bbl, biblio
graphy labels cannot be generated, please correct the citation.
Package biblatex Warning: citation '2' was not found at all in the .bbl, biblio
graphy labels cannot be generated, please correct the citation.
LaTeX Warning: Empty bibliography on input line 206.
Package biblatex Warning: Please rerun LaTeX.
(biblatex)                Page breaks have changed. 
```

**Comment by RLumSK** [comment]
@Dr-Joe-Roberts So the reason for not showing the publications is clear, just the cause is weird. 
Have you tried to delete all files in your folder with the Rmd-file except the Rmd-file itself before re-running the build process?

**Comment by Dr-Joe-Roberts** [comment]
@RLumSK Yes, this seems to resolve the issue. Any ideas as to why?

**Comment by mitchelloharawild** [comment]
My best guess is that from my experience when a *.tex file exists, it can change the way in which a document is knitted. The *.tex file is often left over from when there was an error in knitting (or if the `keep_tex` argument was set). By deleting this file the knitting process was started anew, allowing the issue to be resolved. Just a theory.

**Comment by Dr-Joe-Roberts** [comment]
Great, thanks!
