### ISSUE TITLE
Update example for RORCID to account for records with differing dimensions

### ISSUE THREAD

**Issue by ConnorJPSmith** [ropenscilabs/vitae#74]
In the instructions, there is an example of using `rorcid` to get education history:

```
orcid_data <- do.call("rbind",
  rorcid::orcid_educations("0000-0002-2140-5352")$`0000-0002-2140-5352`$`affiliation-group`$summaries
)
```

This works, but in my case there was an issue where one of the education records has 29 columns and the other has 30 columns. the `do.call('rbind',...)` fails.

**Comment by ConnorJPSmith** [comment]
I haven't worked out the best way to fix it yet, but for an example of this issue you can use my ORCID:

0000-0003-2187-1262

**Comment by Dr-Joe-Roberts** [comment]
@ConnorJPSmith  This may not be what you're looking for but I have had good success with replacing this with:
```
get_edu <- bind_rows(
orcid_educations("0000-0002-9576-9239")$`0000-0002-9576-9239`$`affiliation-group`$summaries
)
```

**Comment by mitchelloharawild** [comment]
Using bind_rows would be my suggestion - it has better capabilities for handling inconsistent columns in the data.
