### ISSUE TITLE
How to add more space before name (title)? 

### ISSUE THREAD

**Issue by OmarGonD** [ropenscilabs/vitae#76]
I'm using vitae package to make my CV. However, my name is very close to the top.

How should I add more spacing between the top and my name.

I've found that I can use this in pure Latex to increase the top spacing:

`\usepackage[scale=0.75,top=1cm]{geometry}`

But getting this error:

```
tlmgr search --file --global "/tikzlibrarytopaths.code.tex"
C:\texlive\2018\texmf-dist\scripts\texlive\tlmgr.pl: TLPDB::from_file could not download http://ftp.inf.utfsm.cl/pub/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb;
C:\texlive\2018\texmf-dist\scripts\texlive\tlmgr.pl: maybe the repository setting should be changed.
! LaTeX Error: Can be used only in preamble.

Error: Failed to compile omar_gonzales_diaz_mktg.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See omar_gonzales_diaz_mktg.log for more info.
Execution halted
```

See picture for more reference:

https://i.stack.imgur.com/caoTS.jpg

**Comment by mitchelloharawild** [comment]
You should be able to use the `geometry` option in the YAML header like most other rmarkdown documents.

````
---
geometry: "scale=0.75,top=1cm"
---
````

https://stackoverflow.com/questions/13515893/set-margin-size-when-converting-from-markdown-to-pdf-with-pandoc
